// Generated by gencpp from file ros_master_test/Wrc201Msg.msg
// DO NOT EDIT!


#ifndef ROS_MASTER_TEST_MESSAGE_WRC201MSG_H
#define ROS_MASTER_TEST_MESSAGE_WRC201MSG_H

#include <ros/service_traits.h>


#include <ros_master_test/Wrc201MsgRequest.h>
#include <ros_master_test/Wrc201MsgResponse.h>


namespace ros_master_test
{

struct Wrc201Msg
{

typedef Wrc201MsgRequest Request;
typedef Wrc201MsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wrc201Msg
} // namespace ros_master_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_master_test::Wrc201Msg > {
  static const char* value()
  {
    return "43791c45179089218511643bd58fdb58";
  }

  static const char* value(const ::ros_master_test::Wrc201Msg&) { return value(); }
};

template<>
struct DataType< ::ros_master_test::Wrc201Msg > {
  static const char* value()
  {
    return "ros_master_test/Wrc201Msg";
  }

  static const char* value(const ::ros_master_test::Wrc201Msg&) { return value(); }
};


// service_traits::MD5Sum< ::ros_master_test::Wrc201MsgRequest> should match
// service_traits::MD5Sum< ::ros_master_test::Wrc201Msg >
template<>
struct MD5Sum< ::ros_master_test::Wrc201MsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_master_test::Wrc201Msg >::value();
  }
  static const char* value(const ::ros_master_test::Wrc201MsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_master_test::Wrc201MsgRequest> should match
// service_traits::DataType< ::ros_master_test::Wrc201Msg >
template<>
struct DataType< ::ros_master_test::Wrc201MsgRequest>
{
  static const char* value()
  {
    return DataType< ::ros_master_test::Wrc201Msg >::value();
  }
  static const char* value(const ::ros_master_test::Wrc201MsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_master_test::Wrc201MsgResponse> should match
// service_traits::MD5Sum< ::ros_master_test::Wrc201Msg >
template<>
struct MD5Sum< ::ros_master_test::Wrc201MsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_master_test::Wrc201Msg >::value();
  }
  static const char* value(const ::ros_master_test::Wrc201MsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_master_test::Wrc201MsgResponse> should match
// service_traits::DataType< ::ros_master_test::Wrc201Msg >
template<>
struct DataType< ::ros_master_test::Wrc201MsgResponse>
{
  static const char* value()
  {
    return DataType< ::ros_master_test::Wrc201Msg >::value();
  }
  static const char* value(const ::ros_master_test::Wrc201MsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_MASTER_TEST_MESSAGE_WRC201MSG_H
