twist_mux:
  publisher:
    topic: "/rover_drive"

  subscribers:
    edge_cmd_vel:
      topic: "/edge_cmd_vel"
      priority: 100
      timeout: 0.5

    nav_cmd_vel:
      topic: "/nav_cmd_vel"
      priority: 50
      timeout: 0.5

  locks: []

